<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Create Operaciones' => '',
    'Create Roles' => '',
    'Create User' => '',
    'Created At' => '',
    'Delete' => '',
    'Email' => '',
    'I forgot my password' => '',
    'ID' => '',
    'Id Operacion' => '',
    'Id Rol' => '',
    'Id Role Operacion' => '',
    'Inactive' => '',
    'Nom Operacion' => '',
    'Nom Rol' => '',
    'Operaciones' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Please fill out the following fields to signup:' => '',
    'Reset' => '',
    'Roles' => '',
    'Save' => '',
    'Search' => '',
    'Signup' => '',
    'Status' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update Operaciones: {nameAttribute}' => '',
    'Update Roles: {nameAttribute}' => '',
    'Update User: {nameAttribute}' => '',
    'Updated At' => '',
    'Username' => '',
    'Users' => '',
    'select_option' => '',

    'clientOptionsButtons' => [
        'dom' => 'lfrtipB',
        'buttons' => ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5'],
        'language' => [
            "lengthMenu" => 'showing' . " _MENU_ " . 'rows_per_page',
            "zeroRecords" => 'no_records_found',
            "info" => 'showing' . " _PAGE_ " . 'of' . " _PAGES_",
            "infoEmpty" => 'no_records_available',
            "infoFiltered" => "(" . 'filtering_for' . ")",
            "search" => 'search' . " :",
            "paginate" => [
                "first" => 'first',
                "last" => 'last',
                "next" => 'next',
                "previous" => 'previous',
            ],
        ],
    ],
];
