<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activo' => '',
    'Are you sure you want to delete this item?' => '',
    'Auth Key' => '',
    'Categoria' => '',
    'Categorias' => '',
    'Create Categorias' => '',
    'Create Productos' => '',
    'Create Sub Categoria' => '',
    'Create User' => '',
    'Created At' => '',
    'Delete' => '',
    'Email' => '',
    'Estado Categoria' => '',
    'Estado Producto' => '',
    'Estado Sub Categoria' => '',
    'ID' => '',
    'Id Categoria' => '',
    'Id Departamento' => '',
    'Id Municipio' => '',
    'Id Producto' => '',
    'Id Sub Categoria' => '',
    'Inactivo' => '',
    'Nom Departamento' => '',
    'Nom Municipio' => '',
    'Nom Producto' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Precio: {0, number, integer}' => '',
    'Precio: {0}' => '',
    'Precio: {0}, Cantidad: {1}, Subtotal: {2}' => '',
    'Productos' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Status' => '',
    'Sub Categoria' => '',
    'Sub Categorias' => '',
    'The requested page does not exist.' => '',
    'Tu edad es: {age}' => '',
    'Update' => '',
    'Update Categorias: {nameAttribute}' => '',
    'Update Productos: {nameAttribute}' => '',
    'Update Sub Categoria: {nameAttribute}' => '',
    'Update User: {nameAttribute}' => '',
    'Updated At' => '',
    'Username' => '',
    'Users' => '',
    'aqui {cats, plural, =0{no hay gatos} =1{hay un gato} other{hay # gatos}}' => '',
    'hola, {username}' => '',
    'select_option' => '',
];
