<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'filtering_for' => 'filtering_for',
    'first' => 'primero',
    'last' => 'último',
    'next' => 'siguiente',
    'no_records_available' => 'no_records_available',
    'no_records_found' => 'no_records_found',
    'of' => 'de',
    'previous' => 'anterior',
    'rows_per_page' => 'rows_per_page',
    'search' => 'buscar',
    'showing' => 'mostrando',
    'Active' => 'Activo',
    'Are you sure you want to delete this item?' => '¿Estás seguro de que deseas eliminar este elemento?',
    'Auth Key' => 'Auth Key',
    'Create Operaciones' => 'Crear Operaciones',
    'Create Roles' => 'Crear Roles',
    'Create User' => 'Crear usuario',
    'Created At' => 'Creado en',
    'Delete' => 'Eliminar',
    'Email' => 'Correo electrónico',
    'I forgot my password' => 'Olvidé mi contraseña',
    'ID' => 'ID',
    'Id Operacion' => 'Id Operacion',
    'Id Rol' => 'Id Rol',
    'Id Role Operacion' => 'Id Role Operacion',
    'Inactive' => 'Inactivo',
    'Nom Operacion' => 'Nom Operacion',
    'Nom Rol' => 'Nom Rol',
    'Operaciones' => 'Operaciones',
    'Password Hash' => 'Password Hash',
    'Password Reset Token' => 'Token de restablecimiento de contraseña',
    'Please fill out the following fields to signup:' => 'Complete los siguientes campos para registrarse:',
    'Reset' => 'Restablecer',
    'Roles' => 'Roles',
    'Save' => 'Guardar',
    'Search' => 'Buscar',
    'Signup' => 'Signup',
    'Status' => 'Estado',
    'The requested page does not exist.' => 'La página solicitada no existe.',
    'Update' => 'Actualizar',
    'Update Operaciones: {nameAttribute}' => 'Actualizar operaciones: {nameAttribute}',
    'Update Roles: {nameAttribute}' => 'Actualizar roles: {nameAttribute}',
    'Update User: {nameAttribute}' => 'Actualizar usuario: {nameAttribute}',
    'Updated At' => 'Actualizado en',
    'Username' => 'Nombre de usuario',
    'Users' => 'Usuarios',
    'select_option' => 'Seleccione opción',

    'clientOptionsButtons' => [
        'dom' => 'lfrtipB',
        'buttons' => ['copyHtml5', 'excelHtml5', 'csvHtml5', 'pdfHtml5'],
        'language' => [
            "lengthMenu" => 'mostrando' . " _MENU_ " . 'registros por página',
            "zeroRecords" => 'no_se_encontrarón_registros',
            "info" => 'mostrando' . " _PAGE_ " . 'de' . " _PAGES_",
            "infoEmpty" => 'no_hay_registros_disponibles',
            "infoFiltered" => "(" . 'filtrando_para' . ")",
            "search" => 'buscar' . " :",
            "paginate" => [
                "first" => 'primero',
                "last" => 'último',
                "next" => 'siguiente',
                "previous" => 'anterior',
            ],
        ],
    ],
];